package spl.requiresanalysis;

public enum InterpretationCategory {
    REQUIRES_PLAUSIBLE,
    SAME_FEATURE_PLAUSIBLE,
    SHARED_SUPPORT_PLAUSIBLE,
    SHARED_DOMAIN_MODEL,
    STRUCTURAL_EXTENDS,
    STRUCTURAL_IMPLEMENTS,
    COMMON_CONTEXT,
    CO_OCCURRING_FEATURES_PLAUSIBLE,
    INFRASTRUCTURE_ONLY,
    INTRA_BLOCK,
    INSUFFICIENT_EVIDENCE
}
