package spl.requiresanalysis;

public enum RequiresCandidateStatus {
    ELIGIBLE_REQUIRES_EVIDENCE,
    SAME_SIGNATURE_DIRECTED_DEPENDENCY,
    INTRA_ENTITY,
    INTRA_CLASS,
    INTRA_BLOCK,
    INTRA_ASSET_MANDATORY_TARGET,
    MANDATORY_SOURCE_TO_VARIABLE_TARGET,
    INTRA_ASSET_ROOT_DEPENDENCY,
    COMMON_TARGET_DEPENDENCY,
    SIGNATURE_INCONSISTENT,
    UNRESOLVED_BLOCK_SCOPE,
    UNRESOLVED_ENTITY,
    INVALID_DEPENDENCY_KIND,
    SELF_DEPENDENCY
}
